# Generated by Django 2.1.1 on 2022-01-07 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Bitcoin',
        ),
        migrations.DeleteModel(
            name='Deposits',
        ),
        migrations.DeleteModel(
            name='Paypal',
        ),
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
