# Generated by Django 2.1.1 on 2022-01-14 00:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_fusion_invest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invest',
            new_name='Transaction',
        ),
    ]
