# Generated by Django 2.1.1 on 2022-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20220117_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fusion',
            name='deposit',
        ),
        migrations.AddField(
            model_name='balance',
            name='fee',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='fusion',
            name='balance',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='fusion',
            name='capital',
            field=models.IntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='fusion',
            name='profit',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
